### ISSUE TITLE
PermissionError: [WinError 5] Accesso negato

### ISSUE THREAD

**Issue by Sh4d0wm4st3r** [Nearata/vvvvid-downloader#2]
Qunado uprovo a scaricare una serie, mi esce il seguente errore:

Traceback (most recent call last):
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\site-packages\vvvvid_downloader\__main__.py", line 250, in <module>
    main()
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\site-packages\vvvvid_downloader\__main__.py", line 159, in __call__
    sp_run([
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Accesso negato

Sbaglio qualcosa?

**Comment by Nearata** [comment]
@Sh4d0wm4st3r hai i permessi per scrivere in quella cartella? hai provato un altra cartella?

**Comment by Sh4d0wm4st3r** [comment]
Sì, ho provato con cartelle assegnando permessi ad Everyone, ho provato a dare il medesimo permesso alla cartella di Pyton, ho provato usando il prompt dei comandi con permessi amministrativi, ma niente. Mi ritorna sempre il medesimo errore.

**Comment by easly1989** [comment]
Stesso problema anche per me.
Se può essere di aiuto, il problema ce l'ho con qualsiasi downloder da VVVVID (come quello di CoffeeStraw).
Indagando un po, sembra che dipenda da **ytdl**, ma non essendo proprio il mio campo, potrei sbagliare

**Comment by Nearata** [comment]
Quando lo script vi chiede di inserire il percorso di FFmpeg, avete tutti inserito il percorso diretto al file `ffmpeg.exe` ?

esempio:

```sh
D:\ffmpeg\bin\ffmpeg.exe
```

Se invece avete la variabile d'ambiente, assicuratevi di averla creata nel modo corretto.

esempio (Path):

```sh
D:\ffmpeg\bin
```

Al momento, lo script non controlla se la variabile d'ambiente / percorso diretto siano validi.

**Comment by Nearata** [comment]
Risolto in `1.3.0`.
