### ISSUE TITLE
PermissionError: [WinError 5] Accesso negato

### ISSUE THREAD

**Issue by BLUSKY70** [Nearata/vvvvid-downloader#4]
Buonasera non riesco a venirne fuori , mi date un aiuto?
`Windows PowerShell
Copyright (C) Microsoft Corporation. Tutti i diritti riservati.

Prova la nuova PowerShell multipiattaforma https://aka.ms/pscore6

PS C:\Users\loris\Documents\PlatformIO\Projects\TEST_FINESTRA> C:/Users/loris/AppData/Local/Programs/Python/Python38/python.exe c:/Users/loris/Documents/PlatformIO/Projects/TEST_FINESTRA/src/main.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\loris\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "c:/Users/loris/Documents/PlatformIO/Projects/TEST_FINESTRA/src/main.py", line 17, in str_arm
    run(["C:/Users/loris/Documents/ArduinoData/packages/arduino/tools/avrdude", '-CC:/Users/loris/Documents/ArduinoData/packages/arduino/tools/avrdude/6.3.0-arduino17/etc/avrdude.conf', "-v", "-patmega328p", "-carduino", "-PCOM5", "-b115200", "-D", "-Uflash:w:C:/Users/loris/Documents/PlatformIO/Projects/MOV_ARM/.pio/build/uno/firmware.hex:i"])
  File "C:\Users\loris\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\loris\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\loris\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Accesso negato`. Come risolvo ?

**Comment by Nearata** [comment]
Ciao,

lo script non trova FFmpeg nel sistema. Ho rilasciato una nuova versione per ovviare a questo problema.

Risolto nella versione `1.3.0`.
